language: csharp
solution: AquaMate.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./AquaMate.sln

script:
  - xbuild ./AquaMate.sln /p:Configuration=Debug /p:Platform="x86" /p:CIMode=true /p:MonoCS=true /verbosity:minimal
  - nunit-console ./AquaMate.Tests/bin/Debug/AquaMate.Tests.dll
