language: csharp
solution: AquaLog.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./AquaLog.sln

script:
  - xbuild ./AquaLog.sln /p:Configuration=Debug /p:Platform="x86" /p:CIMode=true /p:MonoCS=true /verbosity:minimal
  - nunit-console ./AquaLog.Tests/bin/Debug/AquaLog.Tests.dll
