os: Visual Studio 2017

version: 1.1.0.{build}
configuration: Debug
platform: x86

pull_requests:
  do_not_increment_build_number: true

environment:
  CIMode: true

skip_commits:
  files:
    - ALSketch/*
    - deploy/*
    - libs/*
    - locales/*
    - '**/*.md'

before_build:
  - nuget restore ./AquaLog.sln

build_script:
  - msbuild ./AquaLog.sln /p:Configuration=Debug /p:Platform="x86" /p:CIMode=true /p:MonoCS=true /verbosity:minimal

test_script:
  - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"nunit-console-x86.exe" -targetdir:".\AquaLog.Tests\bin\Debug" -targetargs:"AquaLog.Tests.dll /noshadow" -output:"coverage.xml" -filter:"+[*]* "

after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml" -X gcov
