image: Visual Studio 2015

version: 1.4.0.{build}
configuration: Debug
platform: x86
skip_tags: true

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

environment:
  CIMode: true

install:
  - nuget install NUnit.Runners -OutputDirectory packages
  - nuget install OpenCover -OutputDirectory packages
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov

skip_commits:
  files:
    - ALSketch/*
    - deploy/*
    - libs/*
    - locales/*
    - '**/*.md'

before_build:
  - nuget restore ./AquaMate.sln

build_script:
  - msbuild ./AquaMate.sln /p:Configuration=Debug /p:Platform="x86" /p:CIMode=true /p:MonoCS=true /verbosity:minimal

test_script:
  - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register -target:"packages\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console.exe" -targetdir:".\AquaMate.Tests\bin\Debug" -targetargs:"AquaMate.Tests.dll" -output:".\coverage.xml" -filter:"+[*]* "
  - codecov -f "coverage.xml" -X gcov
