os: Visual Studio 2017

version: 1.1.0.{build}
configuration: Debug
platform: x86

pull_requests:
  do_not_increment_build_number: true

environment:
  CIMode: true

before_build:
  - nuget restore ./AquaLog.sln

build_script:
  - msbuild ./AquaLog.sln /p:Configuration=Debug /p:Platform="x86" /p:TargetFrameworkVersion=v4.0 /p:CIMode=true /p:MonoCS=true /verbosity:minimal

test_script:
  - nunit-console-x86 ./AquaLog.Tests/bin/Debug/AquaLog.Tests.dll /framework:net-4.5

after_test:
  - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"nunit-console-x86.exe" -targetdir:"C:\projects\AquaLog\AquaLog.Tests\bin\Debug" -targetargs:"AquaLog.Tests.dll /noshadow /framework:net-4.5" -output:"coverage.xml" -filter:"+[*]* "
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml" -X gcov
